import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { Toaster } from 'react-hot-toast';
import SplashCursor from './Components/SplashCursor/SplashCursor';
import NavbarPage from "./NavbarPage/page";
import Footer from "./Components/Footer/Footer";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased font-poppins bg-dark`}
      >

        <div className="bg-dark">
          <SplashCursor />
          <NavbarPage />
          <Toaster />
          {children}
          <Footer/>
        </div>
      </body>
    </html>
  );
}